set_property PACKAGE_PIN U13 [get_ports en_led_0]
set_property PACKAGE_PIN V11 [get_ports enable_0]
set_property PACKAGE_PIN U14 [get_ports {sw_in_0[2]}]
set_property PACKAGE_PIN V14 [get_ports {sw_in_0[1]}]
set_property PACKAGE_PIN T13 [get_ports {sw_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_en_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_en_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_en_0[0]}]
set_property PACKAGE_PIN H17 [get_ports {led_en_0[0]}]
set_property PACKAGE_PIN K15 [get_ports {led_en_0[1]}]
set_property PACKAGE_PIN J13 [get_ports {led_en_0[2]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clock_IBUF_BUFG]
